### ISSUE TITLE
Any plans to get this merged upstream?

### ISSUE THREAD

**Issue by DarkDefender** [meshonline/Surface-Heat-Diffuse-Skinning#1]
I'm just wondering if you would try to get it merged into blender.

This solves a really annoying problem and at least I think that I would be nice to replace the current auto weight code with this.

The devs might be quite busy with 2.8 not though. But I'm sure it will not be impossible.

**Comment by meshonline** [comment]
The two algorithms are different, the result of this add-on is not as good as Blender's built-in auto weighting tool in some cases, so it can not replace current auto weight function in Blender.

**Comment by DarkDefender** [comment]
Ok, thanks clearing things up. :)

Shall I close this or leave it open?
