### ISSUE TITLE
Always FileNotFoundError when I hit the Surface Heat Diffuse Skinning button

### ISSUE THREAD

**Issue by xamxixixo** [meshonline/Surface-Heat-Diffuse-Skinning#2]
The message is:

Traceback (most recent call last):
  File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\surface_heat_diffuse_skinning.py", line 190, in execute
    self.write_mesh_data(objs, os.path.join(bpy.utils.script_path_user(), "addons", "surface_heat_diffuse_skinning", "data", "untitled-mesh.txt"))
  File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\surface_heat_diffuse_skinning.py", line 60, in write_mesh_data
    f = open(filepath, 'w', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\abc\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\surface_heat_diffuse_skinning\\data\\untitled-mesh.txt'

location: <unknown location>:-1

**Comment by meshonline** [comment]
Let the file explorer show hidden files and directories temporarily, check if the directory of ''C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\surface_heat_diffuse_skinning\data' exists.

If it doesn't exist, please download the pre-built version.

If it exists, please report the OS version, I'll check it.

**Comment by xamxixixo** [comment]
Thank you. Sorry I forgot to copy the bin and data to the addon directory. But still it occurs this error, and the mesh which is needed to be skinned has been rotated and scaled randomly. The OS is Windows 10 64 bit

Traceback (most recent call last):
  File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\surface_heat_diffuse_skinning.py", line 228, in execute
    close_fds = ON_POSIX)
  File "C:\Users\abc\Desktop\3D\Blender\blender-2.79.0-git20180716.b85be88655c-windows64\2.79\python\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\abc\Desktop\3D\Blender\blender-2.79.0-git20180716.b85be88655c-windows64\2.79\python\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

location: <unknown location>:-1

**Comment by meshonline** [comment]
Maybe you forgot to build the binary from the 'src' and copy shd.exe to 'bin/Windows'.

**Comment by xamxixixo** [comment]
Yes indeed. Thank you now it works without error. Just the mesh still randomly rotated and scaled.

P/S: Ah, I fixed the randomly rotate and scale. It's all fine now.

**Comment by immeasurability** [comment]
Hi! can u help me pls how to do this step (build the binary from the 'src' and copy shd.exe to 'bin/Windows')
i cant find any tutors how to do that(((

**Comment by philstopford** [comment]
The process is documented : https://github.com/meshonline/Surface-Heat-Diffuse-Skinning/blob/master/src/Readme.txt

You can also find the pre-built package here : https://blendermarket.com/products/voxel-heat-diffuse-skinning

**Comment by immeasurability** [comment]
ok. now
Traceback (most recent call last):
  File "C:\Users\Ra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\surface_heat_diffuse_skinning.py", line 227, in execute
    close_fds = ON_POSIX)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Не удается найти указанный файл

location: <unknown location>:-1

**Comment by philstopford** [comment]
I would expect that you don't have the binary properly installed in the right folder structure, hence 'FileNotFoundError'. If you look in the Python code (surface_heat_diffuse_skinning.py) at line 227, you'll see a path is being built by joining together various strings, including a platform indicator (Windows/Mac/Linux). You need to have the binary you compiled in the resulting path, for the script to be able to find it.

If this path is not found, the error is generated at line 227.

**Comment by immeasurability** [comment]
gg done i dont get step 3. (Maybe you forgot to build the binary from the 'src' and copy shd.exe to 'bin/Windows'.)

**Comment by philstopford** [comment]
So, are you getting things working now, or are you still having trouble?

**Comment by immeasurability** [comment]
yes all work, i just test this produc, but result bad for me((( 

![screenshot_5](https://user-images.githubusercontent.com/20519543/52284893-604c3e80-2976-11e9-9d5b-60cc21c04d77.png)

![screenshot_4](https://user-images.githubusercontent.com/20519543/52284558-b2d92b00-2975-11e9-9260-daf0479697cc.png)

**Comment by philstopford** [comment]
I had better results with the voxel approach compared to the surface diffusion.

**Comment by immeasurability** [comment]
what does it mean? that this addon is not suitable for most (((

**Comment by immeasurability** [comment]
Well, then I do not understand what is selling for 40$? is this result?

**Comment by philstopford** [comment]
Take a look at the docs : http://www.mesh-online.net/voxel.html

There's an overview of the difference that the voxel approach makes to the skinning. For me, the voxel approach produced good results every time. The voxel approach appears to be only in the BlenderMarket release. The github project offers the surface diffusion approach, which has limitations.

**Comment by immeasurability** [comment]
it turns out if I buy this addon, then I will have a good result?

**Comment by philstopford** [comment]
Nothing is guaranteed, but Blender Market does have a 30 day refund policy : https://support.blendermarket.com/buying/refund-policy

**Comment by immeasurability** [comment]
ok u say u get better results
if u have second time test this file https://www.dropbox.com/s/dy0s9mb2nt1v7x4/test.000.blend?dl=0

**Comment by philstopford** [comment]
Default values for the voxel addon.
![default_voxel_values](https://user-images.githubusercontent.com/1983851/52287452-2eb48280-2938-11e9-92d6-633dfb820b26.png)

**Comment by immeasurability** [comment]
drop me pls look at file in editor how bind skin or screen at mouth open
