### ISSUE TITLE
Any chance this will be updated to work with blender 2.80 beta?

### ISSUE THREAD

**Issue by spiraloid** [meshonline/Surface-Heat-Diffuse-Skinning#3]

**Comment by meshonline** [comment]
It used to work on the early version of Blender 2.8, but the API changed, it does not work any more, I will look into the new API to try to solve the issue. Thanks for your report.

**Comment by spiraloid** [comment]
if it helps.

https://youtu.be/Mjy-zGG3Wk4

**Comment by meshonline** [comment]
This is the experiment version, sometimes you need to run it twice to get the correct result.
http://www.mesh-online.net/280/surface_heat_diffuse_skinning.py

**Comment by meshonline** [comment]
Fixed the issue, the latest version:
http://www.mesh-online.net/280/surface_heat_diffuse_skinning.py
The user interface will appear in 'View3D->UI->Mesh Online' tab of the sidebar.

**Comment by meshonline** [comment]
Just moved the panel to the sidebar, please download the script again.
