### ISSUE TITLE
Help---cannot build project from source code

### ISSUE THREAD

**Issue by nigelmerle** [meshonline/Surface-Heat-Diffuse-Skinning#4]
I tried to follow your tutorial but i cannot compile the files. also the menus do not show in blender 3.0.
 Is it possible to send me the already compiled file to my email address. 
i am having a nightmare with cygwin, im a non programmer

nigelmerlin@hotmail.com

cheers

**Comment by nigelmerle** [comment]
I want to share with you the version of the addon that I am using in blender 3.0 that I am using so that you can find out why your version doesn’t work in my blender , I hope this can help you to improve your addon. Let me know if you find something useful

**Comment by meshonline** [comment]
I have confirmed the bug, thank you.
BTW. Please remove the shared link of v3.1.1.zip, for it is the older paid version, which should not be shared.

**Comment by meshonline** [comment]
Please re-download the pre-built package, I have fixed the bug:)

**Comment by nigelmerle** [comment]
> Please re-download the pre-built package, I have fixed the bug:)

done, I cant thank you enough for looking into this. I hope this will help many people out there who are having the same issues.
BTW what is the difference between the paid version and your version ?

**Comment by nigelmerle** [comment]
i noticed that i have only this window in the tool now : the surface heat diffuse skinning but the voxel heat diffuse skinning window doesnt show up. I would be happy if we could keep both of them because sometimes I used a mix of both when surface heat diffuse skinning doesnt weight paint correctly in some areas. 
I see a new option detect solidify, what is it used for ?

**Comment by meshonline** [comment]
Sorry I can't keep both of them in the package, for the voxel skinning part is only included in the paid product.
The new option is for dealing with solidified clothes.

**Comment by meshonline** [comment]
Sorry I can't keep both of them in the package, for the voxel skinning part is only included in the paid product.
The paid product includes three parts: surface skinning, voxel skinning, and corrective smooth baker.
The new option is for dealing with solidified clothes.

**Comment by nigelmerle** [comment]
Ok but since i already have the paid version could you do one specially for
me and send me it by email?

**Comment by meshonline** [comment]
You can upgrade for FREE via FastSpring or BlenderMarket.
[https://www.mesh-online.net/voxel.html](https://www.mesh-online.net/voxel.html)

Where To Buy
Github(Last updated on November 27, 2020): new
Surface Heat Diffuse Skinning - Blender Add-on v3.1.3 (FREE)
 
Blender Market(Last updated on June 28, 2021): new
[Blender Market Store - Voxel Heat Diffuse Skinning - Blender Add-on v3.3.0](https://blendermarket.com/products/voxel-heat-diffuse-skinning) ($30)
 
FastSpring's Digital Store(Last updated on June 28, 2021): new
[FastSpring Store - Voxel Heat Diffuse Skinning - Blender Add-on v3.3.0](http://sites.fastspring.com/meshonline/product/voxelheatdiffuseskinningblenderaddon) ($30)
