### ISSUE TITLE
This Error shows up everytime I press Surface Heat Diffuce Skinning

### ISSUE THREAD

**Issue by JamJamel** [meshonline/Surface-Heat-Diffuse-Skinning#8]
I'm a bit of a newbie in Blender so I decided to try this addon. After hitting the 'Surface Heat Diffuse Skinning' button, there is an error message (And I don't understand any of it).
The message says:

Python: Traceback (most recent call last):
  File "C:\Users\jamel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\surface_heat_diffuse_skinning\__init__.py", line 173, in modal
    self.read_weight_data(self._objs, os.path.join(os.path.dirname(__file__), "data", "untitled-weight.txt"))
  File "C:\Users\jamel\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\surface_heat_diffuse_skinning\__init__.py", line 120, in read_weight_data
    f = open(filepath, 'r', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jamel\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons\\surface_heat_diffuse_skinning\\data\\untitled-weight.txt'

**Comment by meshonline** [comment]
The add-on only support the official version of Blender, if you install Blender from Microsoft App Store, it will fail to run the add-on.

If you are using the official Blender, and still encountered this error, the command-line utility may failed to run, in this case, please test with a simple 3d model and an simple armature, to see if it can run successfully.

**Comment by JamJamel** [comment]
I downloaded the official version of Blender and it worked just fine! Thank you so much!
